name: Powershell tests

on:
  push:
    branches:
      - "*"

jobs:
  run-powerhsell-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PowerShell (latest)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common curl

          curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc

          curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/microsoft-prod.list

          sudo apt-get update
          sudo apt-get install -y powershell

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.4"

      - name: Verify PowerShell Installation
        shell: pwsh
        run: echo $PSVersionTable

      - name: Run Tests
        run: go test ./...
